scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.3
    max_x:  0.3
    min_y: -0.3
    max_y:  0.3
    min_z:  0.0
    max_z:  0.2
